nodeLinker: node-modules

packageExtensions:
  "@strapi/strapi@*":
    dependencies:
      esbuild: "^0.25.0"
  "esbuild-register@*":
    peerDependencies:
      esbuild: "*"
  "@strapi/core@*":
    dependencies:
      "@strapi/strapi": "*"
  "@strapi/admin@*":
    dependencies:
      "@strapi/strapi": "*"
  "@strapi/plugin-users-permissions@*":
    dependencies:
      "@strapi/strapi": "*"
  "@strapi/plugin-cloud@*":
    dependencies:
      "@strapi/strapi": "*"
  "@strapi/data-transfer@*":
    dependencies:
      "@strapi/strapi": "*"
